# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-17 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default='123', max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(max_length=32, verbose_name='用户名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='xxx',
            field=models.CharField(max_length=32, verbose_name='类型名称'),
        ),
    ]
